<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Skeleton index</title>
        <link rel="stylesheet" type="text/css" href="<?php echo ROOT_PATH; ?>/lib/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="<?php echo ROOT_PATH; ?>/css/custom.sticky.footer.css">
    </head>
<body>
    
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Skeleton</a>
            </div>
        </div>
    </div>
    
    <div class="footer">
        <div class="container">
            <p class="text-muted">&copy; ACME 2014</p>
        </div>
    </div>

    <script src="./lib/js/jquery-1.11.1.min.js"></script>
    <script src="./lib/js/bootstrap.min.js"></script>
</body>
</html>